# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "jackd"
email: jack.driscoll@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A 'simple' page about me, Jack'D (Jack Driscoll), from Milwaukee, WI in Turtle Island ("USA"). Also home to content from guest writers Fitz Twombly, nTeleKy and Lupa.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jack.ethertech.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nteleky
github_username: jack-driscoll

# Maybe??? add image, embiggen SEO
defaults:
  - scope:
      path: ""
      type: posts
    values:
      image:
        path: /images/mythic_support_twitter.png
        width: 514
        height: 270
        alt: "Support From The Mythic Zone - Lupa the WereWolf and Fitz the WereDeer helping you"
      seo_description_max_words: 200
        
# Set author
author:
  name: jackd
  url: https://jackd.ethertech.org/

# Set default twitter account to resident artist Fitz Twombly
  username: 'nteleky'
  card: summary-large-image

# Share some information about jackd's socials
social:
  name: Jack Driscoll
  links:
    - https://github.com/jack-driscoll

# OKOKOK S E O, now back to the good stuff BUILD SETTINGS
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

# you can manually specify which elements you want included
includes:
#  - head
  - images

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile (quick someone get me a trash can or a paper bag)
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Honestly not sure how to use these
#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234
#  facebook: 1234
